jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Go to Project
          command: 'cd iz-1'
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing CppCheck
          command: 'apt-get update && apt-get install -y cppcheck'
      - run:
          name: Installing Valgrind
          command: 'apt-get update && apt-get install -y valgrind'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build --target Google_Tests_run -- -j 6'
      - run:
          name: Start CppCheck
          command: 'cppcheck src/* include/* Google_tests/AbsoluteDateTest'
      - run:
          name: Start Tests With Valgrind
          command: 'valgrind build/Google_tests/Google_Tests_run'
