jobs:
  install:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run: apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
      - run: apt-get update && apt-get install -y gcc g++
      - run: apt-get update && apt-get install -y cppcheck
      - run: apt-get update && apt-get install -y valgrind
      - run: apt-get update && sudo apt-get install -y cmake
      - run: apt-get update && apt-get install -y gcovr
    - persist_to_workspace:
                  root: .
                  paths:
                      - .
  build:
    docker: 
      - image: "debian:stretch"
    steps:
      - attach_workspace:
                  at: .
      - checkout
      - run: ls -la && mkdir iz-1/build && cd iz-1/build && 
                    cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=--coverage -DCMAKE_C_FLAGS=--coverage -G "CodeBlocks - Unix Makefiles" .. && ls -la
      - run: cmake --build iz-1/build --target Google_Tests_run -- -j 6 && ls -la
      - persist_to_workspace:
                  root: .
                  paths:
                      - .
  test:
    docker: 
      - image: "debian:stretch"
    steps:
      - attach_workspace:
                  at: .
      - checkout
      - run:
          name: Start CppCheck
          command: 'ls -la && cd iz-1 && ls -la && cppcheck src/* include/* Google_tests/AbsoluteDateTest'
      - run:
          name: Start Tests With Valgrind
          command: 'valgrind iz-1/build/Google_tests/Google_Tests_run'
      - run:
          name: Gcovr
          command: 'cd iz-1 && gcovr -r .'

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build
