jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing CppCheck
          command: 'apt-get update && apt-get install -y cppcheck'
      - run:
          name: Installing Valgrind
          command: 'apt-get update && apt-get install -y valgrind'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'mkdir iz-1/build && cd iz-1/build && cmake -H. -Bbuild .. && ls -la'
